language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script: phpunit --configuration phpunit.xml

install:
  - composer install
  - git clone https://github.com/OpenMage/magento-mirror.git magento
  - cd magento && git checkout tags/1.9.1.0 && cd -
