language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - MAGENTO_VERSION="1.9.1.0"

install:
  - composer install
  - git clone https://github.com/OpenMage/magento-mirror.git magento
  - cd magento && git checkout tags/${MAGENTO_VERSION} && cd -
  - cp ./tests/composer.magento.json ./magento/composer.json
  - cd magento && composer install && cd -
  - cd magento && ./vendor/bin/composerCommandIntegrator.php magento-module-deploy && cd -

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
