language: php
php:
  - 5.5
  - 5.6
  - hhvm

script: phpunit --configuration phpunit.xml

env:
  - MAGENTO_VERSION="1.9.1.0"

install:
  - composer install

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
