language: php
php:
  - 5.5
  - 5.6
  - hhvm

script: phpunit --configuration phpunit.xml

env:
  - MAGENTO_VERSION="1.9.1.0"
  - MAGENTO_VERSION="1.9.0.1"

install:
  - composer install
  - git clone https://github.com/OpenMage/magento-mirror.git magento
  - cd magento && git checkout tags/${MAGENTO_VERSION} && cd -
  - cp ./tests/composer.magento.json ./magento/composer.json
  - cd magento && composer require --no-update  magento-hackathon/magento-composer-installer=2.1.1 && cd -
  - cd magento && composer install && cd -
