#!/usr/bin/env php
<?php
/**
 * Magento Module test harness
 *
 * @author Sam Schmidt
 * @date 2015-04-17
 * @company Linus Shops
 */

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

$composerPaths = array(
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
);

foreach ($composerPaths as $file) {
    if (file_exists($file)) {
        define('PROPHET_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('PROPHET_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require PROPHET_COMPOSER_INSTALL;

$composer = json_decode(file_get_contents(__DIR__.'/composer.json'), true);

define('PROPHET_ROOT_DIR', __DIR__);

use Symfony\Component\Console\Application;

$application = new Application();

$application->setName('Prophet');
$application->setVersion('0.8.4');
$application->setDefaultCommand('run');

//Test framework implementations
$application->add(new LinusShops\Prophet\Commands\Run());

//Test setup
$application->add(new LinusShops\Prophet\Commands\Analyze());
$application->add(new \LinusShops\Prophet\Commands\Show());

//Utilities
$application->add(new LinusShops\Prophet\Commands\Init());
$application->add(new LinusShops\Prophet\Commands\IdeHelper());

//Frameworks
$application->add(new \LinusShops\Prophet\Commands\Framework\Install());
$application->add(new \LinusShops\Prophet\Commands\Framework\Show());
$application->add(new \LinusShops\Prophet\Commands\Framework\Update());
$application->add(new \LinusShops\Prophet\Commands\Framework\Remove());

$application->run();
